<!--
Chapter 3 - Methods
-->

```{r setup3, echo=FALSE}
pacman::p_load(tidyverse, thesisdown, knitr, kableExtra)

# Set how wide the R output will go
options(width = 70)
```

# Data and Methods {#methods}

## Data and processing {#data}

In order to transfer the theoretical model set up in Section \@ref(conceptual_model) into a statistical model that can be used to empirically investigate the price elasticity of space heating demand, data from various sources were combined and processed.

**Energy billing data**

The key dataset in this process is a large-scale building-level panel of energy bills made available though the Climate Policy Department at DIW Berlin. The data originates from the energy- and billing service provider ista Deutschland GmbH and was provided for scientific use.[^31] The sample contains information on multi-unit residential buildings in Germany and ranges from 2003 to 2019. The smallest buildings observed have two living units; single-family houses with just one unit are not observed. The observations in the dataset represent annual heating bills at the building-level. The dataset contains the two main variables for the analysis: space heating demand and energy prices. It also contains additional building-level information on the heating surface, the energy carrier, and a building ID and the billing dates to create a panel data structure. While the demand data is available from the start, energy prices are first observed in 2007. Thus, the time period analysed in this thesis ranges from 2007 to 2019.

[^31]: Due to the sensitivity of the data, it is to be classified as confidential. Access was exclusively via DIW Berlin's internal servers. Due to data protection regulations, it is not possible to make the data available to external parties for the purpose of reproducing the results.

**Space heat demand (kWh/sqm/a):** The demand data in the billing dataset is provided as total energy consumed per building and per annual billing period in kilowatt hours (kWh). To isolate the share of energy consumed for the key purpose of space heating, the share of energy used for hot water production is deduced for those buildings where hot water production is also done via the central heating system. In a second step, in order to obtain a comparable metric for the differently sized buildings in the sample, the total space heating demand at building level is divided by the building heating surface in square meters (sqm). This results in the annual space heat demand per square meter as the demand variable. For a summary of the variables and their data sources see Table \@ref(tab:variables).

**Energy prices (Cents/kWh):** The structure of the price data in the dataset is similar to that of energy demand. Total annual costs in Euros are given at the building-level. Based on the relative consumption shares for space heating and hot water generation, the share of space heating in the total costs can be isolated. In a second step, the proportional costs for space heating is converted into per-unit costs by dividing them by the respective amount of space heating consumed in kWh. To make the cost scale more intuitive, it is transferred from Euros to Cents. This gives a per-unit cost in Cents per kWh. A breakdown according to fixed and variable cost components is not reported in the data. Additionally, energy prices are provided in nominal prices thus in order to obtain real prices, nominal prices are adjusted using the German annual consumer price index (CPI) with 2015 as the index year [@destatis21].

**(Billing) Year:** The billing data contains the exact dates of the billing period of an individual building. While most billing periods mirror the calendar year, some buildings have billing periods occurring during the year. Therefore, the start and end dates of the billing periods are used to make an allocation to billing years. For billing periods during the year, the allocation is based on which of the two calendar years contains the majority of days in the billing period.

**Energy carrier:** There are three main groups of energy sources included in the data: Gas, Oil and District Heating. In order to obtain these three overarching categories, the individual energy source descriptions from the original data set are combined under these categories. In addition, all buildings with other heating sources whose occurrence is insignificant compared to the other three categories (e.g. electricity, coal combustion) are grouped under the category *Others*, which is later excluded from the analysis due to the heterogeneity of the group.

**Heating surface (sqm):** Information on the heating surface of a building is given as square meters at building level. The heating area does not correspond to the total floor area of a building, as it excludes the unheated areas within the buildings (e.g., building corridors or basements).

\begin{table}[]
\centering
\caption{Variables and data sources}
\label{tab:variables}
\resizebox{\textwidth}{!}{%
\begin{tabular}{@{}lllll@{}}
\toprule
\textbf{Variable} & \textbf{} & \textbf{Type} & \textbf{Unit} & \textbf{Data source} \\ \midrule
 &  &  &  &  \\
\textit{\begin{tabular}[c]{@{}l@{}}Demand\\ (building-level)\end{tabular}} & Space heat demand & Continuous & ln(kWh/sqm) & Ista \\
\textit{} &  &  &  &  \\
\textit{\begin{tabular}[c]{@{}l@{}}Price\\ (building-level)\end{tabular}} & Energy price & Continuous & ln(cents/kWh) & Ista \\
\textit{} &  &  &  &  \\
\multirow{4}{*}{\textit{\begin{tabular}[c]{@{}l@{}}Billing data\\ (building-level)\end{tabular}}} & Heating surface & Continuous & ln(sqm) & Ista \\
 & Energy carrier & Categorical & Gas / Oil / District heating & Ista \\
 & Building ID & Categorical & - & Ista \\
 & Year & Categorical & - & Ista \\
\textit{} &  &  &  &  \\
\multirow{3}{*}{\textit{\begin{tabular}[c]{@{}l@{}}EPC data\\ (building-level)\end{tabular}}} & Construction year & Continuous & - & Ista (EPC sample) \\
 & Heating system installation year & Continuous & - & Ista (EPC sample) \\
 & Renovation & Categorical & - & Ista (EPC sample) \\
\textit{} &  &  &  &  \\
\textit{\begin{tabular}[c]{@{}l@{}}Climatic conditions\\ (postal code area)\end{tabular}} & Degree days & Continuous & ln(degree days) & IWU (2021) \\
\textit{} &  &  &  &  \\
\multirow{3}{*}{\textit{\begin{tabular}[c]{@{}l@{}}Socio-economic factors\\ (district-level)\end{tabular}}} & Average household income & Continuous & ln(Euros/a) & Statistische Ämter (2021) \\
 & Retirement rate & Continuous & \% & DESTATIS (2021) \\
 & Population density & Continuous & ln(inhabitants/sq. km) & DESTATIS (2021) \\ \bottomrule
\end{tabular}%
}
\end{table}

\ 

**Supplementary data sources**

**Degree days:** Degree days were retrieved from an tool provided by the *Institut für Wohnen und Umwelt (IWU)* at the postal code level [@iwu21]. The data from the IWU-tool originates from the 800 weather stations of the German Meteorological Service (DWD) and are provided on a monthly basis. Within the Excel-based tool the settings of a mean room temperature of 20°C and a heating limit of 15°C are chosen to reflect the VDI based definition of degree days [@vdi13]. In addition, an assignment of the postal code area to the three nearest DWD weather stations with weighting according to geographical distance is chosen in order to better take into account possible distortions due to differences in altitude between a single weather station and the centroid of a postal code area. The extracted monthly degree day figures per postal code area are then aggregated to annual periods on a rolling basis and matched with the annual building-level energy billing observations.



Spatial and temporal distribution:

In Appendix \@ref(fig:buildings-distribution) the spatial and temporal distribution of observations is shown on the district-level. On the temporal dimension, structurally fewer observations of around 40,000 are available in 2007 and 2008, as price data were first recorded in these years. In the decade between 2009 and 2019, a minimum of 201,856 and an average of 239,183 buildings are observed annually, with good spatial coverage. There are only a few districts where no buildings are observed within a year, and for most district-year combinations more than 10 and up to more than 10,000 buildings are observed.



## Estimation methods and empirical model design {#empirical_model}

**Establishing causality**

**Endogeneity issues**


Prices: Form nominal --> real


There is considerable debate in the literature whether household energy demand depends on the marginal or average price, which may differ in the presence of fixed fee and block pricing. Shin (1985) argues that households will respond to average price, which is easily calculated from the electricity bill, rather than to the actual block marginal price, which is costly to determine, and develops an empirical strategy for testing this conjecture. The average price is also used in Metcalf and Hassett (1999),5 and Borenstein (2008, 2009) and Ito (2010) find no evidence that consumers “bunching up” around the block where the price changes, as one would expect if consumers truly respond to marginal price. If demand is assumed to depend on the marginal block price, then price and consumption are simulta-neously determined, and instrumental variable estimation techniques must be used (Burtless and Hausman, 1978; McFadden et al., 1978; Wilder and Willenborg, 1975; Hewitt and Hanemann, 1995; Reiss and White, 2005).
For lack of exact information about the block rates faced by the consumers, however, we are forced to use average price. 


Zu Blockpreisen:
Blockpreise stellen eine gesonderte Ausprägungsform von Paketpreisen dar, und sind beispielsweise bei Stromlieferanten vorzufinden (ebd.). Hier ändern sich die Preise je Mengenintervall, d.h. im Beispiel der Stromversorger nimmt der Preis mit steigendem Mengenintervall ab. Die Idee dahinter ist die, dass die Nachfrage nach Energieversorgung zwar mit zunehmender Haushaltsgröße steigt, die Zahlungsbereitschaft für die gewünschte Menge beim Ausgangspreis jedoch sinkt, sodass durch Blockpreise dieses Dilemma ausgeglichen werden kann und somit zusätzliche Gewinne generiert werden können (ebd., S.288).

Aus Alberini (2011):
An additional concern is whether usage decisions depend on the price in the current (billing) period, on that of earlier periods, or a moving average of the prices of recent periods (Poyer and Williams, 1993).For good measure, in what follows we experiment with current price, as well as price of the previous period.


**Frequentist estimation approaches**

In line with the previous literature [@meier_rehdanz10; @schmitz_madlener20], the fixed-effects model takes the following form:

```{=tex}
\begin{equation}
ln(D)_{it} = \alpha + \beta ln(P)_{it} + \gamma X_{it} + \delta_i + \eta_t + \varepsilon_{it}
(\#eq:fixedeff)
\end{equation}
```


**Bayesian estimation approaches**

## Workflow {#workflow}

Since we model conditional demand only, the results should be considered as short-term elasticities. In contrast, medium- and long-term income elasticities tend to be higher. Households with increased income are likely to move into larger homes over the medium term, which would increase their heating expenditures as well (Nesbakken 1999).  --> Short-run elasticities as a lower bar estimate that produces a conservative estimate.


Csereklyei (2020):
It is widely anticipated that responses in electricity consumption to changes in prices will be rather slow, as it takes time for energy-using durable stock to change (Miller and Alberini, 2016). Thus, short-run or annual price elasticity estimates are expected to be rather inelastic, while one anticipates significantly larger long-run estimates.

Miller and Alberini (2016) furthermore report that the use of IV estimates can change the reported elasticities by up to 80%.


All from Labanderira et al.

discrete decision to purchase durable goods that consume energy and the decision to consume energy is rarely considered. 
renovations may disturbe the picture the panel data provides

On the other hand, most empirical studies in this area have used single-equation econometric models that require separability re- strictions. This is a severe disadvantage as it is not possible to estimate cross-price effects between different energy products or consider the effects of non-energy products on the price elasticity of energy goods. 


Sample period. It is widely accepted that the economic cycle has a strong influence on energy consumption due to income and (indirect cycle-related) price effects. In the case of economic crises, for example, a depression of energy prices may occur; reduced dis- posable income may lead agents to reduce consumption through improvements in energy efficiency, adjustments to other types of consumption or changes towards other more inexpensive energy goods.


From Aufhammer wegen IV approach:
We instrument the utilities’ consumer-facing prices with the weekly average spot price of natural gas at a major natural gas distribution hub in Louisiana (the Henry Hub). This instrument is valid, as we know the formula of how utilities pass-through the price (providing a strong first stage), and the price is determined prior to within-bill consumption (strengthening the exclusion restriction).

No change in the energy taxation (Energiesteuergesetz) in the observed period; letzte Neufassung aus 2006 mit Effekten für 2007

Miller Alberini (2016):
We also find that aggregating our data can result in both higher and lower price elasticity estimates, depending on the dataset used, and that controlling for unit-level fixed effects with panel data generally results in more inelastic demand functions. Addressing the endogeneity of price and/or measurement error in price with instrumental variables has a small but noticeable effect on the price elasticities. Finally, controlling for housing characteristics and capital stock produces a lower price elasticity.
