<!--
Chapter 6 - Discussion
-->

```{r setup6, echo=FALSE}
pacman::p_load(tidyverse, thesisdown, knitr, kableExtra)

# Set how wide the R output will go
options(width = 70)
```

# Discussion {#discussion}

## Discussion of Empirical Results {#discussion-results}

**Findings on the price elasticity of space heating demand**

The first research question which this thesis aimed to answer is: How does a change in the price of energy affect the level of space heating demand? Put differently, the fist research question aims at determining an estimate of the price elasticity of space heating demand.

The results presented previously confirm the assumption that the demand for space heating is a highly inelastic. In the final model Specification in the analysis based on the full sample, the price elasticity was estimated such that the demand for space heating would decrease by -0.243% if the energy price increased by 1% (see Chapter \@ref(full-sample-results)). This means that the overall price elasticity estimated from the full set of data is lower than estimates from previous studies focusing on Germany, most of which estimate an elasticity between -0.3 and -0.6 (see Chapter \@ref(review)). Interestingly, however, the estimated overall price elasticity mirrors the results by @auffhammer_rubin18, the only other previous study that also relies on energy billing data. This might suggest that the previous studies on Germany which are based on social survey data, and therefore involve no observation-specific information on energy prices, overstate actual demand responses. Furthermore, the fact that the price elasticity estimates observed in the different model Specifications moved downwards when the grouping variables for buildings and years were included either as fixed-effects in the full sample or with a partial pooling approach for the Bayesian regression analysis of the subsample is consistent with findings also made by others in the literature [e.g., @miller_alberini16].

Due to the very large sample size of more than 2.7 million observations in the full sample analysis and its inversely proportional relationship to the standard error of a model, the standard error of the price elasticity estimates is very small and does not necessarily reflect the true uncertainty and dispersion about the different combinations of price and demand observed in the data. The uncertainty and dispersion becomes more apparent when looking at the results for the stratified random subsample (see Chapter \@ref(subsample-results)). Even though the estimates for the price elasticity of demand are not directly comparable due to the different sample composition, the final model Specification (bm.2), which does not yet include the interaction term, clearly shows that the prediction for price elasticity as a single parameter is rather narrow, but that the prediction interval becomes significantly wider when the residual error term of a model is included (see Figure \@ref(fig:elasticity-predictions-bm2)).

In addition, it is also necessary to discuss the estimated elasticity that results when the price of the previous period, rather than the price of the same period, is used to determine the price elasticity of space heating demand. The results of the analysis of the full sample show that the estimated elasticity becomes even far more inelastic, dropping from -0.243 when using the same period price to -0.071 when using the previous period price. This means that if one assumes that the price from the previous year informs the demand decision of inhabitants, because they were made aware of the prices through the last energy bill, the demand response is considerably more limited. However, it remains questionable whether a direct comparison of the two elasticity estimates is appropriate. Due to the need to have two consecutive billing observations (energy price in $t-1$ and other variables in $t$), about 0.7 million observations are removed from the sample in the model with the price lag. In contrast to the dropped observations, buildings that appear consecutively in the sample may have special characteristics (e.g., only larger buildings). This may introduce a bias compared to the full sample used in the other model Specifications. Moreover, it remains questionable whether the information obtained from a previous year's bill is actually more informative for residents about energy prices than their monthly prepayments in the current billing period together with the reporting of energy prices in the media or via other information channels. Nevertheless, to incorporate the estimate, one could use it, for example, as a lower bound of the price responsiveness when doing sensitivity testing with more than one estimate.

In summary, the inelastic results found for the price elasticity of space heating demand indicate that households do adjust their demand to the incremental price changes that occurred during the period under investigation, but only to a rather limited extent. Transferring this finding to the effects of price-related policy instruments, such as the BEHG recently introduced in Germany for the building sector to price carbon externalities, means that the direct demand effect to be expected is relatively limited in the short-term. Importantly, for the case of renter households that are observed here, the short-term elasticity may also reflect the long-term elasticity under the current design of the BEHG. As the carbon price is currently only borne by renters, who generally have limited options to make structural changes to the thermal conditions of their housing and change the heating technology, no additional long-term effect can be expected. However, this aspect is discussed further later in this section (see Chapter \@ref(policy-context)).

In addition, it should be pointed out once again that the historical period examined in this thesis is characterized by a gradual change in energy prices. Accordingly, the estimates for the price elasticity of space heating demand can only be transferred to the current situation of energy and especially natural gas scarcity in Europe to a limited extent. At the same time, the effects of the current strong price increases for residential heating energy on the price elasticity are anything but clear. On the one hand, it can be assumed that the strong public attention to energy prices probably leads to a promotion of energy-efficient behavior, which in turn would result in a more elastic demand. At the same time, the strong price increases have a particularly strong impact on the budget of low- and middle-income households, which is an additional factor likely to contribute to a more elastic demand. On the other hand, the price increase is also so strong that households may not be able to reduce their demand further in order to maintain a minimum level of comfort, which in turn would have the opposite effect on the elasticity. Overall, the price elasticities of space heating demand presented in this thesis can provide an empirical starting point also for an analysis of the current crisis situation. However, the underlying structural difference in price development and the limited transferability that this may entail should be made clear.

**Heterogeneity between the energy carrier groups**

Furthermore, this thesis also intended to provide evidence on the additional research question whether there any potential factors for heterogeneity in the sample that may not be reflected in the estimation of an overall mean price elasticity of demand?

Through the analysis of the subsample multiple variables were investigated for potential heterogeneity in price responsiveness. It was found that the type of energy carrier used within a building represented a relevant dimension for varying price elasticities of demand. The interaction term model used to quantify this difference showed that buildings with an oil heating system are associated with a price elasticity of -0.16 [-0.23; -0.10] (mean estimate [95%CI]) and thus have the lowest price responsiveness. Buildings with a gas heating system have a price elasticity of -0.35 [-0.40; -0.29], implying a medium price responsiveness, but higher than the elasticity found for the full sample. And buildings with a district heating system show a price elasticity of -0.53 [-0.60; -0.46] and thus represent the group with the highest price responsiveness. Since the model comparison showed that the model interacting energy price and energy carrier group had the best model fit, the elasticities should be considered as more precise than the overall elasticity for the full sample, when having information on the type of energy carrier.

The underlying reasons for the varying price elasticities of demand between the three energy carrier groups are not fully obvious. However, there are some lines of arguments that may serve as partial explanations. For the highly inelastic demand reaction found for oil one possible reason may be that the market prices for oil in the period under investigation were much more volatile than for the other two energy carrier groups. This volatility may have led people to view price volatility as more of a normal and familiar state of affairs and no longer adjusted their demand based on price movements. A second explanation could be that the oil prices observed in the sample are probably less correlated with the current market prices for oil, since oil, unlike gas and district heating, which are on-demand fuels, is usually stored in the building and the price for new supplies is usually mixed with the price for the remaining heating oil stock. These stock effect might obscure the demand reactions within buildings with an oil heating.




Besides the heterogeneity found for the energy carrier groups, there appears to be no to little heterogeneity in the sample for the other variables considered (e.g., households in colder regions in Germany do not systematically deviate in their energy demand response to changing energy prices from households in warmer regions)



The different posterior distributions reflect the results of the visual examination of the simple linear relationship. The most inelastic demand response is found for buildings with oil heating -0.16 [-0.23; -0.10] (Mean estimate [95%CI]). For buildings with gas as the energy carrier type, the estimates are in a medium range of -0.35 [-0.40; -0.29]. For buildings with district heating, demand is most elastic with estimates of -0.53 [-0.60; -0.46].


**Little heterogeneity for other determinants**


**Effects of other determinants on space heat demand**

The results from the full sample analysis are also suitable to discuss the second research question: What other determinants do affect the level space heating demand and need to be considered so that their effects are not falsely attributed to energy prices? The empirical analysis considered a set of additional variables, most of which showed a relevant association with the demand for space heating. The most relevant effect on the model results was clearly related to the inclusion of unobserved inter-individual differences between the units (buildings) and also an intra-individual dynamic over time (years) either trough fixed effects in the full sample analysis or trough the partial pooling approach in the subsample analysis. The model comparison conducted for the subsample analysis showed how significantly the model fit increased. Furthermore, the relatively minor effects on the price elasticity of demand when estimating the model Specifications with price as a sole predictor and then with the other variables included showed that the 

The 




RQ2:




## Integration into the Policy Context {#policy-context}


This implies that, rental households -- which are observed in this thesis -- are price takers when it comes to price-related policy instruments for space heating, which means that a socially desirable and politically feasible decarbonisation of the building sector cannot be implemented via the CO2 price alone [@braungardt_etal21]. 

Haushalte können nur dann auf eine Preisänderung reagieren, wenn ihnen diese bekannt/ bewusst ist. Es ist somit zu erwarten, dass die Preiselastizitäten höher sind, wenn eine transparente Kommunikation der Preise/Kosten vorliegt.

In Mietendenhaushalten sind die Möglichkeiten zur Veränderung der energetischen Qualität der Gebäudehülle sowie des Heizungssystems in der Regel sehr eingeschränkt, so dass zu erwarten ist, dass die langfristigen Preiselastizitäten deutlich niedriger sind als in selbstgenutzten Gebäuden





Der Verbrauch von Fernwärme lässt sich auch in Kubikmeter (m3) Gas umrechnen. Erdgas hat einen Heizwert von etwa 10 kWh/m3. 100 kWh entsprechen circa 10 m3 Erdgas. Es ist allerdings wenig sinnvoll, den Fernwärme-Verbrauch einfach in einen Gas-Verbrauch umzurechnen. Denn im Vergleich zu Erdgas oder Heizöl fallen keine zusätzlichen Verluste abhängig vom Wirkungsgrad des Kessels an. Daher ist der Fernwärmeverbrauch immer 10 bis 20 Prozent günstiger als bei fossilen Energieträgern. Besser vergleichen können Sie die durchschnittlichen Heizkosten pro m2 mit unseren Vergleichsartikeln.

. Given the robustness of these findings, this paper provides tight bounds on a policy-relevant parameter key to applications ranging from estimating the welfare benefits of fracking (Hausman and Kellogg 2015) to analyzing the regressivity of two-part tariffs (Borenstein and Davis 2012).


**Points from the literature (to be integrated)**

- Policy implication: Low elasticity estimates (lower than found in the previous literature) indicate that there is a strong need for a policy mix and carbon pricing must be accompanied by strong measures to induce THG reductions in the buildings sector

- 



Relevante Stellen für Rückbezüge aus der Literatur:

- In their analysis, @labandeira_etal17 include a total of 428 papers, all published between 1990 and 2016. For the demand of natural gas, they find an average short-term (long-term) price elasticity of -0.18 (-0.57) based on 230 individual estimates. And for heating oil they find a comparable average short-term (long-term) elasticity of -0.19 (-0.54), which, however, is based on only 44 individual estimates [@labandeira_etal17]. An average elasticity for space heating -- which is less focused on in the literature due to its relatively low prevalence -- is not provided.

- There are three earlier studies that have a spatial focus on Germany. The first study was conducted by @rehdanz07, who estimates short-term price elasticities for different energy carrier groups for residential space heating demand. She uses social survey data on household-level heating expenditures from the Socio-Economic Panel (SOEP) in the years 1998 and 2003. Methodologically, a cross-sectional statistical analysis with dummy variables is conducted for the two years. In contrast to the  meta-estimates presented in the previous part of the Chapter, the study finds that demand for heating oil is highly elastic with estimates ranging between -1.68 and -2.03, depending on the model specification. For gas, the results indicate an inelastic elastic demand between -0.44 and -0.63 (depending on the model specification) which is nevertheless significantly more elastic than the meta-estimates presented previously. Therefore, the study concludes that the type of energy carrier can have a strong influence on the price sensitivity of households [@rehdanz07].


**The role of energy prices and interaction with complementary measures (policy-mix)**


- For district heating larger share of costs are fixed; may drive the effect of larger price elasticities as data does not differentiate between fixed and variable cost components and with lower energy demand the per-unit cost rate increses due to the larger 

- Prices not the only option for action, potential overestimation of price relevance

- Warmmietenmodell (Now only the renters are effected which will mainly trigger short-term price reactions; for decarbonisation need to tap the long-term channel; Lessors must be incentivized to initialize efficiency measures; one option: split prices but then long-term price signal is still partly muted; Warmmietmodell as an alternative where both parties renters and lessors have full economic incentive of pricing measures)


Relevance of Policy Mix - UBA (2022) study:

- Simulate the effect of various price paths for the BEHG until 2030 and simulate for the buildings sector (also consider the transportation and industry sector) how those varying price paths affect the level of sectoral emissions.

- Shortcoming: They do not consider demand effects from price changes --> short-term effects that this theses argues for; prices are only endogenous effects on the long-term investment desicions.

- Additional Shortcoming: Simulate choice of heat supply system, but not additional renovations, for example of the building envelope

- With the findings from this thesis it must therefore be assumed that actual emissions would be lower than simulated in the model not considering demand adjustments from higher energy prices

- Three scenarios: 1. BaU CO2 price of 125€/t in 2030; 2. Foresight, anticipation of energy prices for coming 5/10 yrs; 3. Foresight AND shorter lifetimes of heating systems (75% of usual life-time) for increased replacement.

- BaU: 86 Mt CO2e in 2030, KSG 2021 sector goal for buildings: 67 Mt CO2e in 2030; 28.4% above the target

- Only the scenarios with adjusted replacement rates + foresight meet or fall below the KSG (2021) targets (amended 2021 version).

- Anticipation of higher CO2 prices over long time span has high impact; but effect about three times as large when combined with shorter lifetimes of heating systems

- In scenarios with the assumption that heat supply systems are replaced more quickly due to the rising CO2 price, the heating replacement rate increases to around 5%. In sensitivities in which no shorter lifetimes of the heat supply systems are assumed, the heating replacement rate is significantly lower.

- Investitionsentscheidungen sind bedarfsgetrieben --> Policy Mix kann hier abhilfe Schaffen (bonus-malus system)

- Another key finding is that significantly greater savings can be achieved if the capital good is replaced before the end of its respective service life. Due to the long-term capital stocks, the effects are greatest in the buildings and industry sectors, while in the transport sector the additional effect of early replacement is limited due to the comparatively short holding periods of vehicles.

- Zusammenspiel: nur wenn fossile Investitionsgüter wirtschaftlich unattraktiv sind, wird durch die Austauschratenerhöhung die gewünschte Wirkung erzielt. Zusätzloiche Maßnahmen könnten sein: Verbesserung von Informationsverfügbarkeit, Ordnungsrecht oder finanzielle Förderungen. Besondere Bedeutung ist dabei einem verlässlich kommunizierten Preispfad des BEHG zuzumessen.

- Das im Rahmen der aktuellen Beratungen zum Fit-for-55-Paket der EU zu erwartende verschärfte, neue ESR-Ziel wie auch die daraus abgeleitete neue BEHG-Höchstmenge wird in keiner CO2-Preissensitivität eingehalten.--> Einhaltung der ambitionierteren BEHG-Ziele höhere CO2-Preise als hier analysiert zu erwarten sind bzw. darüberhinausgehende klimapolitische Instrumente erforderlich sind

- Damit bestätigt sich mit dieser Modellierungsarbeit auch die wirtschaftstheoretische Herleitung (vgl. Kemfert et al. (2021)), dass zur Erreichung der Klimaschutzziele ein Politik-Mix zielführend ist, welcher die CO2-Bepreisung mit ordnungsrechtlichen Instrumenten, Förderprogrammen und weiteren Instrumenten (z.B. dem Abbau klimaschädlicher Subventionen) kombiniert.







All the models described represent the conditional demand. It therefore has to be inferred that the results reflect the short-term price elasticities of demand. The use of other dynamic estimation approaches to estimate long-term elasticities, as for example @alberini_etal11 or @csereklyei20 have done, would go beyond the scope of this thesis and are therefore not pursued. Additionally, the short-term price elasticities estimated here may also be viewed as lower bound estimates of the price responsiveness compared to the usually higher long-term estimates. As they are a lower bound estimate, they can also be considered as a conservative estimate for any kind of modelling or policy advice for which they might be used.