<!--
Chapter 7 - Conclusion
-->

```{r setup7, echo=FALSE}
pacman::p_load(tidyverse, thesisdown, knitr, kableExtra)

# Set how wide the R output will go
options(width = 70)
```

# Conclusion {#conclusion}

This thesis investigated short-term price elasticities of space heating demand based on a large-scale sample of energy bills in Germany in the period between 2007 and 2019. The estimation of price elasticities of space heating demand is of relevance as it is a key parameter for assessing the expected impact of price-related energy policy instruments, such as the newly introduced Fuel Emissions Trading Act (BEHG) 2021 in Germany. The novelty of this work is that it relies on energy billing data instead of social survey data, which provides a more accurate picture of energy demand and prices than previous studies, which usually use information on household expenditures and average price data from national statistics to derive demand [e.g., @rehdanz07; @schmitz_madlener20]. Furthermore, this thesis relies on a broad range of statistical methods and applies Bayesian regression analysis with a multilevel partial pooling approach on a subsample of the data. Bayesian methods are well suited to propagate and communicate the uncertainty in the model estimates.

According to the theory of price and demand, the demand for a good is mainly determined by its own price and the price of possible substitute goods [@pindyck_rubinfeld18]. Space heating is to be considered as an essential good, which is associated with a minimum demand in the winter months in order to ensure the well-being of residents. Furthermore, the production of space heating depends on the energetic conditions and heating technologies installed in a building, which cannot be easily replaced in the short-term. This is especially true for rental buildings, where the tenants usually have no direct say regarding renovation activities such as building insulation or a renewal of the heating system. Due to these reasons, the price elasticity of space heating demand can be assumed to be rather inelastic -- especially for the segment of rental buildings observed in this thesis. The theoretical assumption of a rather inelastic demand reaction is also confirmed by previous evidence from the literature. The majority of studies focusing on the specific energy application of space heating demand in the residential buildings sector arrive at estimates for the price elasticity of space heating demand in the range between -0.3 and -0.6 (see Chapter \@ref(review)).

The results of this thesis confirm the assumption that the demand for space heating is a highly inelastic. In the final model Specification in the analysis based on the full sample, the price elasticity was estimated such that the demand for space heating would decrease by -0.243% if the energy price increased by 1% (see Chapter \@ref(full-sample-results)). Thus, the estimated elasticity is even lower than in most previous studies. Furthermore, an exploratory analysis of the heterogeneity of the price response based on a subsample of the data and its formalization through the use of an interaction model found heterogeneity in the demand response of the different energy carrier groups. Buildings with oil heating are associated with the lowest demand elasticity of -0.16 [-0.10; -0.23] (Mean estimate [95%CI]), gas with an elasticity in the mid-range of -0.35 [-0.29; -0.40] and district heating with a still inelastic but higher elasticity of -0.53 [-0.46; -0.60] (see Chapter \@ref(subsample-results)).

For the broader policy context for the decarbonisation of the residential buildings sector, the estimated highly inelastic demand response implies that households are price takers when it comes to price-related policy instruments for space heating, such as the carbon price signal induced by the BEHG. This entails that households have to spend a larger share of their budget to meet their desired demand for space heating and that this effect becomes even more relevant with increasing energy prices. This effect is particularly relevant for the rental building segment, because under the current design of the BEHG, renters are the sole recipients of the carbon price signal -- which in turn means that owners have no incentive to improve the energy conditions of a building or to decarbonise the heat supply. From a policy perspective, there is therefore a need to shift the carbon price signal, at least in part, to building owners to ensure that long-term investment in decarbonising the buildings sector is encouraged alongside short-term demand responses. Furthermore, carbon pricing in the building sector needs to be embedded in a wider policy mix to make the transition to a low-carbon building sector socially desirable and politically feasible. Accompanying and reinforcing instruments include regulatory measures such as the introduction of minimum energy performance standards (MEPS) for buildings and roadmaps for a consecutive phase-out of the installation of new fossil-based heating technologies. Fiscal instruments to promote energy-efficient renovation of the building stock and renewable heating technologies. And the expansion and decarbonisation of district heating supply [SOURCE UBA].

Since the sample data is limited to the rental segment of the buildings sector, the price elasticity estimates presented in this thesis should be considered as elasticities for this specific segment. Due to varying conditions, it can be assumed that the price elasticities for single-family homes, self-owned apartment buildings, and for commercial properties differ from those for rental apartment buildings. By estimating an elasticity for the rental segment specifically, this paper fills a research gap that has been identified in the literature [e.g., @braungardt_etal21]. Beyond Germany, the elasticity estimates from this work may also be relevant for researchers and policy makers in other countries and regions that have comparable conditions in terms of building stock, climatic conditions and energy demand and also face the challenge of decarbonising the buildings sector in the coming decades.

**Limitations**

The main limitation related to this work is that it was not possible to control for the socio-economic determinants of space heating demand at the household-level. Previous studies show that household income in particular is a relevant determinant that could not be taken into account together with other relevant factors such as the number of household members, age or education. At the same time, the billing data underlying this work has been shown to also offer an advantage over previous studies based on social surveys, as it provides specific energy demand and prices. Hence, it would be particularly valuable for the future if both specific energy demand and prices on the one hand and socio-economic factors on the other hand were collected at the household level in dedicated household panels, e.g. through the use of smart meters, in order to produce even more reliable estimates of the price elasticity of space heating demand.

Another limitation of this study is related to the risk that the different price elasticities found between the energy carrier groups could be partly attributable to the higher share of fixed heating cost components at lower levels of energy demand. Due to the absence of a breakdown of costs into fixed and variable components, a more detailed investigation was unfortunately not possible.

**Further research**

Another limitation of the work is that an additional estimation based on an instrumental variable approach was attempted to address a possible simultaneity bias in the data, but was ultimately abandoned because the identifying assumption for a suitable instrument was not met. Further studies could tackle this issue and test other instrumental variables while also using energy billing data, which would potentially eliminate the simultaneity bias.

Another aspect for future research could be to estimate long-term price elasticities of energy demand based on the energy billing data. In this study, due to the limited length of the thesis, only short-term price elasticities of space heating demand were estimated, which represent the conditional demand response. Estimating long-term price elasticities would be an important research question, especially because the specific estimation for the rental segment could verify the assumption made in this thesis that the long-term elasticities for the rental segment are not much higher than the short-term ones and below those of owner-occupied homes.
