---
title: "Short-Term Price Elasticities of Heating Demand: A Statistical Analysis of Consumption Data in Germany"
author: "Marc Blauert"
date: "`r format(Sys.Date())`"
institution: "Humboldt University of Berlin"
division: "Albrecht Daniel Thaer-Institute"
advisor: "Prof. Dr. Karsten Neuhoff"
altadvisor: "Prof. Dr. Tobias Krüger"
department: "Integrated Natural Resource Management (INRM)"
degree: "Master of Science"
knit: bookdown::render_book
site: bookdown::bookdown_site

# Line spacing switch out \onehalfspacing with \singlespacing or \doublespacing, if desired.

header-includes:
    - \usepackage{setspace}\onehalfspacing

# This will automatically install the {remotes} package and {thesisdown}
# Change this to FALSE if you'd like to install them manually on your own.
params:
  'Install needed packages for {thesisdown}': True
  
# Remove the hashtag to specify which version of output you would like.
# Can only choose one at a time.
output:
  thesisdown::thesis_pdf: default 
#  thesisdown::thesis_gitbook: default         
#  thesisdown::thesis_word: default
#  thesisdown::thesis_epub: default

# If you are creating a PDF you'll need to write your preliminary content 
# (e.g., abstract, acknowledgements) below or use code similar to line 25-26 
# for the .RMD files. If you are NOT producing a PDF, delete or silence
# lines 25-39 in this YAML header.

abstract: '`r if(knitr:::is_latex_output()) paste(readLines(here::here("prelims", "00-abstract.Rmd")), collapse = "\n  ")`'
# If you'd rather include the preliminary content in files instead of inline
# like below, use a command like that for the abstract above.  Note that a tab 
# is needed on the line after the `|`.
acknowledgements: |
  People I need to thank: Franziska, Till, Abteilung beim DIW --> Bereitstellung Daten, Betreuer.
#preface: |
#  This is an example of a thesis setup to use the reed thesis document class 
#  (for LaTeX) and the R bookdown package, in general.
  
# Specify the location of the bibliography below
bibliography: bib/references.json

# Download your specific csl file and refer to it in the line below.
csl: csl/apa.csl
lot: true
lof: true

link-citations: true
urlcolor: blue
linkcolor: blue
---

```{r setup0, include=FALSE}
pacman::p_load(tidyverse, thesisdown, knitr, kableExtra)

# Set how wide the R output will go
options(width = 70)
```

```{=html}
<!--
The acknowledgments, preface, dedication, and abstract are added into the PDF
version automatically by inputting them in the YAML at the top of this file.
Alternatively, you can put that content in files like 00--prelim.Rmd and
00-abstract.Rmd like done below.
-->
```

```{r eval=!knitr::is_latex_output(), child=here::here("prelims", "00--prelim.Rmd")}

```

```{r eval=!knitr::is_latex_output(), child=here::here("prelims", "00-abstract.Rmd")}

```

```{=html}
<!-- The {.unnumbered} option here means that the introduction will be 
"Chapter 0." You can also use {-} for no numbers on chapters.
-->
```
